services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-php
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/php.ini
    expose:
      - "80"
    restart: unless-stopped
    depends_on:
    networks:
      - {DOCKER_NETWORK}

volumes:
  db_data:
    driver: local

networks:
  {DOCKER_NETWORK}:
    external: true
